# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gimo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gimo
  pod 'Lock', '~> 1.28'
  pod 'ChameleonFramework'
  pod 'FlatUIKit'
  pod 'UICountingLabel'
  pod 'FCAlertView'

end

target 'gimo WatchKit App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gimo WatchKit App

end

target 'gimo WatchKit Extension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gimo WatchKit Extension

end
